Lexer, parser: pipes and substitutions
kkarnauk/sd-hse-spring-2022 pull request #6
Opened 2022-02-06 09:36 UTC by psurkov

2022-02-06 09:43 UTC, psurkov commented
Если надо можно мёржить сейчас, или я потом допишу в этот же PR двойной лексинг и подстановки мб

2022-02-06 16:57 UTC, kkarnauk requested changes

2022-02-06 16:57 UTC, kkarnauk commented on src/main/kotlin/ru/hse/sd/cli/lang/impl/CommandGrammar.kt
> +    private val assignment by literal and equalToken and literal map { AssignmentCommand(it.t1, it.t3) }
Может быть сделать destructing? Я не понимал, что такое t1 и t3 секунд 10 :(

2022-02-06 16:57 UTC, kkarnauk commented on src/main/kotlin/ru/hse/sd/cli/lang/impl/CommandGrammar.kt
> +    private val pipeChain by leftAssociative(term, pipeToken) { l, _, r ->
Почему тут есть переносы, а нигде больше нет?

2022-02-06 16:57 UTC, kkarnauk commented on src/test/kotlin/ru/hse/sd/cli/lang/impl/CommandParserTest.kt
> +            Arguments.of("x=y", AssignmentCommand("x", "y")),
Надо добавить тесты `echo= 1`, `echo =2`, `echo = 3`

2022-02-09 17:48 UTC, psurkov commented on src/test/kotlin/ru/hse/sd/cli/lang/impl/CommandParserTest.kt
> +            Arguments.of("x=y", AssignmentCommand("x", "y")),
решили что не будем 1в1 делать как в баше и запрещать пробелы вокруг равно

2022-02-09 17:52 UTC, psurkov commented on src/main/kotlin/ru/hse/sd/cli/lang/impl/CommandGrammar.kt
> +    private val assignment by literal and equalToken and literal map { AssignmentCommand(it.t1, it.t3) }
Ок

2022-02-09 17:53 UTC, psurkov commented on src/main/kotlin/ru/hse/sd/cli/lang/impl/CommandGrammar.kt
> +    private val pipeChain by leftAssociative(term, pipeToken) { l, _, r ->
Теперь у ExternalCommand, PipeCommand, assignment

2022-02-09 21:04 UTC, kkarnauk commented on src/test/kotlin/ru/hse/sd/cli/lang/impl/CommandParserTest.kt
> +            Arguments.of("x=y", AssignmentCommand("x", "y")),
Тогда стоит добавить тесты, чтобы зафиксировать это решение

2022-02-09 21:49 UTC, psurkov commented on src/test/kotlin/ru/hse/sd/cli/lang/impl/CommandParserTest.kt
> +            Arguments.of("x=y", AssignmentCommand("x", "y")),
done

2022-02-09 21:49 UTC, merged